name: Test jobs.<job_id>.container.image
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  amazonlinux2:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amazonlinux:2
      credentials:
        username: kenhys
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      #
      # can't run actions/checkout@v4
      # /usr/bin/docker exec  27746d1ada601a300729d196688c3862762c2fd26eaa6ec398c2408272610571 sh -c "cat /etc/*release | grep ^ID"
      # /__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
      # /__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
      # 
      # - uses: actions/checkout@v4
      - name: show os-release
        run: cat /etc/os-release
      - uses: actions/checkout@v3
