name: VirtualBox test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  on_jammy:
    name: CGroup V1 on jammy
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
          label:
            - AmazonLinux/2
            #- AmazonLinux/2023
            - AlmaLinux/9
          include:
            - label: AmazonLinux/2
              image: amazonlinux-2
            #- label: AmazonLinux/2023
            #  image: amazonlinux-2023
            - label: AlmaLinux/9
              image: almalinux-9
    steps:
      - uses: actions/checkout@v4
      - name: Show host information
        run: |
          cat /proc/cpuinfo | grep -E "vmx|svm"
          lsmod | grep kvm
      - name: Set up vagrant
        run: |
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox
          vagrant --version
          vagrant status
      - name: Spin up vagrant
        run: |
          vagrant up --provider virtualbox --debug ${{ matrix.image }}
      - name: Run Test ${{ matrix.label }} on ubuntu-22.04
        run: |
          vagrant ssh ${{ matrix.image }} -- /host/test-yum.sh
  on_macos13:
    name: CGroup V1 on macos-13
    runs-on: macos-13
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Show host information
        run: |
          cat /proc/cpuinfo | grep -E "vmx|svm"
          lsmod | grep kvm
      - name: Set up vagrant
        run: |
          vagrant --version
          vagrant status
      - name: Spin up vagrant
        run: |
          vagrant up --provider virtualbox --debug amazonlinux-2
      - name: Run Test amazonlinux-2 on macos-13
        run: |
          vagrant ssh amazonlinux-2 -- /host/test-yum.sh
  on_macos:
    name: CGroup V1 on macos-latest
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up vagrant
        run: |
          cat /proc/cpuinfo | grep -E "vmx|svm"
          lsmod | grep kvm
          vagrant --version
          vagrant status
      - name: Spin up vagrant
        run: |
          vagrant up --provider virtualbox --debug amazonlinux-2
      - name: Run Test amazonlinux-2 on macos-latest
        run: |
          vagrant ssh amazonlinux-2 -- /host/test-yum.sh
