name: VirtualBox test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  jammy:
    name: CGroup V1 on jammy
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
          label:
            - AmazonLinux/2
            #- AmazonLinux/2023
            - AlmaLinux/9
          include:
            - label: AmazonLinux/2
              image: amazonlinux-2
            #- label: AmazonLinux/2023
            #  image: amazonlinux-2023
            - label: AlmaLinux/9
              image: almalinux-9
    steps:
      - uses: actions/checkout@v4
      - name: Show host information
        run: |
          cat /proc/cpuinfo | grep -E "vmx|svm"
          lsmod | grep kvm
      - name: Set up vagrant
        run: |
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox
          vagrant --version
          vagrant status
      - name: Spin up vagrant
        run: |
          vagrant up --provider virtualbox --debug ${{ matrix.image }}
      - name: Run Test ${{ matrix.label }} on ubuntu-22.04
        run: |
          vagrant ssh ${{ matrix.image }} -- /host/test-yum.sh
  noble:
    name: CGroup V1 on noble
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
          label:
            - AmazonLinux/2
            #- AmazonLinux/2023
            - AlmaLinux/9
          include:
            - label: AmazonLinux/2
              image: amazonlinux-2
            #- label: AmazonLinux/2023
            #  image: amazonlinux-2023
            - label: AlmaLinux/9
              image: almalinux-9
    steps:
      - uses: actions/checkout@v4
      - name: Show host information
        run: |
          cat /proc/cpuinfo | grep -E "vmx|svm"
          lsmod | grep kvm
      - name: Set up virtualbox
        run: |
          sudo apt-get update
          sudo apt-get install -y virtualbox
      - name: Set up vagrant
        run: |
          sudo apt-get update
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt install -y vagrant
          vagrant --version
          vagrant status
      - name: Spin up vagrant
        run: |
          vagrant up --provider virtualbox --debug ${{ matrix.image }}
      - name: Run Test ${{ matrix.label }} on ubuntu-24.04
        run: |
          vagrant ssh ${{ matrix.image }} -- /host/test-yum.sh
  macos13:
    name: CGroup V1 on macos-13
    runs-on: macos-13
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Show host information
        run: |
          system_profiler SPHardwareDataType SPSoftwareDataType
      - name: Set up vagrant
        run: |
          # No vagrant by default
          brew install --cask virtualbox
          brew install hashicorp/tap/hashicorp-vagrant
          vagrant --version
          vagrant status
      - name: Spin up vagrant
        run: |
          vagrant up --provider virtualbox amazonlinux-2
      - name: Run Test amazonlinux-2 on macos-13
        run: |
          vagrant ssh amazonlinux-2 -- /host/test-yum.sh
  macos14:
    name: CGroup V1 on macos-14
    runs-on: macos-14
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Show host information
        run: |
          system_profiler SPHardwareDataType SPSoftwareDataType
      - name: Set up vagrant
        run: |
          # No vagrant by default
          brew install --cask virtualbox
          brew install hashicorp/tap/hashicorp-vagrant
          vagrant --version
          vagrant status
      - name: Spin up vagrant
        run: |
          vagrant up --provider virtualbox amazonlinux-2
      - name: Run Test amazonlinux-2 on macos-latest
        run: |
          vagrant ssh amazonlinux-2 -- /host/test-yum.sh
  macos:
    name: CGroup V1 on macos-15 (macos-latest)
    runs-on: macos-15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Show host information
        run: |
          system_profiler SPHardwareDataType SPSoftwareDataType
      - name: Set up vagrant
        run: |
          # No vagrant by default
          brew install --cask virtualbox
          brew install hashicorp/tap/hashicorp-vagrant
          vagrant --version
          vagrant status
      - name: Spin up vagrant
        run: |
          vagrant up --provider virtualbox amazonlinux-2
      - name: Run Test amazonlinux-2 on macos-15
        run: |
          vagrant ssh amazonlinux-2 -- /host/test-yum.sh
